import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

/**
 * Crown Audio — Install-Focused Product Library
 * DCi Analog, DCi Network (BLU link), DCi DA (Dante), and CDi series.
 * Source: crownaudio.com datasheets and operation manuals, verified July 2026.
 * All DCi are 2U. DCi 8|600 & 4|1250 are deeper (432mm). 2|2400 & 4|2400 are deepest (483mm).
 * Power draw values are maximum AC draw at full rated output per Crown datasheets.
 */
export const templates: DeviceTemplate[] = [

  // ─── DCi ANALOG SERIES ───────────────────────────────────────────────────────

  {
    id: "crown-dci-2-300",
    deviceType: "amplifier",
    label: "DCi 2|300",
    shortName: "DCi 2|300",
    manufacturer: "Crown",
    modelNumber: "DCi 2|300",
    searchTerms: ["crown", "dci", "2|300", "drivecore", "install", "analog", "70v", "2ch", "amplifier"],
    powerDrawW: 750,
    voltage: "100-240V",
    heightMm: 89,    // 2U
    widthMm: 483,
    depthMm: 362,
    weightKg: 8.5,
    referenceUrl: "https://www.crownaudio.com/en-US/products/dci-2-300",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 2, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 2),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-dci-2-600",
    deviceType: "amplifier",
    label: "DCi 2|600",
    shortName: "DCi 2|600",
    manufacturer: "Crown",
    modelNumber: "DCi 2|600",
    searchTerms: ["crown", "dci", "2|600", "drivecore", "install", "analog", "70v", "2ch", "amplifier"],
    powerDrawW: 1500,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 362,
    weightKg: 8.5,
    referenceUrl: "https://www.crownaudio.com/en-US/products/DCi-2-600",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 2, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 2),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-dci-4-300",
    deviceType: "amplifier",
    label: "DCi 4|300",
    shortName: "DCi 4|300",
    manufacturer: "Crown",
    modelNumber: "DCi 4|300",
    searchTerms: ["crown", "dci", "4|300", "drivecore", "install", "analog", "70v", "4ch", "amplifier"],
    powerDrawW: 1500,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 362,
    weightKg: 9.1,
    referenceUrl: "https://www.crownaudio.com/en-US/products/DCi-4-300",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 4),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-dci-4-600",
    deviceType: "amplifier",
    label: "DCi 4|600",
    shortName: "DCi 4|600",
    manufacturer: "Crown",
    modelNumber: "DCi 4|600",
    searchTerms: ["crown", "dci", "4|600", "drivecore", "install", "analog", "70v", "4ch", "amplifier"],
    powerDrawW: 3000,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 362,
    weightKg: 9.1,
    referenceUrl: "https://www.crownaudio.com/en-US/products/dci-4-600",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 4),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-dci-8-300",
    deviceType: "amplifier",
    label: "DCi 8|300",
    shortName: "DCi 8|300",
    manufacturer: "Crown",
    modelNumber: "DCi 8|300",
    searchTerms: ["crown", "dci", "8|300", "drivecore", "install", "analog", "70v", "8ch", "amplifier"],
    powerDrawW: 3000,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 362,
    weightKg: 10.7,
    referenceUrl: "https://www.crownaudio.com/en-US/products/dci-8-300",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 8, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 8),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-dci-8-600",
    deviceType: "amplifier",
    label: "DCi 8|600",
    shortName: "DCi 8|600",
    manufacturer: "Crown",
    modelNumber: "DCi 8|600",
    searchTerms: ["crown", "dci", "8|600", "drivecore", "install", "analog", "70v", "8ch", "amplifier"],
    powerDrawW: 6000,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 432,
    weightKg: 13.6,
    referenceUrl: "https://www.crownaudio.com/en-US/products/8300",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 8, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 8),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-dci-4-1250",
    deviceType: "amplifier",
    label: "DCi 4|1250",
    shortName: "DCi 4|1250",
    manufacturer: "Crown",
    modelNumber: "DCi 4|1250",
    searchTerms: ["crown", "dci", "4|1250", "drivecore", "install", "analog", "70v", "4ch", "amplifier"],
    powerDrawW: 6000,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 432,
    weightKg: 13.6,
    referenceUrl: "https://www.crownaudio.com/en-US/product_families/dci-drivecore-series",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 4),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  // ─── DCi NETWORK SERIES (BLU link) ───────────────────────────────────────────

  {
    id: "crown-dci-2-300n",
    deviceType: "amplifier",
    label: "DCi 2|300N",
    shortName: "DCi 2|300N",
    manufacturer: "Crown",
    modelNumber: "DCi 2|300N",
    searchTerms: ["crown", "dci", "2|300n", "drivecore", "network", "blu link", "hiqnet", "70v", "2ch", "amplifier"],
    powerDrawW: 750,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 362,
    weightKg: 8.5,
    referenceUrl: "https://www.crownaudio.com/en-US/products/dci-2-300n",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 2, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 2),
      port("BLU link 1", "ethernet", "bidirectional"),
      port("BLU link 2", "ethernet", "bidirectional"),
      port("Control Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-dci-2-600n",
    deviceType: "amplifier",
    label: "DCi 2|600N",
    shortName: "DCi 2|600N",
    manufacturer: "Crown",
    modelNumber: "DCi 2|600N",
    searchTerms: ["crown", "dci", "2|600n", "drivecore", "network", "blu link", "70v", "2ch", "amplifier"],
    powerDrawW: 1500,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 362,
    weightKg: 8.5,
    referenceUrl: "https://www.crownaudio.com/en-US/products/dci-2-600n",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 2, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 2),
      port("BLU link 1", "ethernet", "bidirectional"),
      port("BLU link 2", "ethernet", "bidirectional"),
      port("Control Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-dci-4-300n",
    deviceType: "amplifier",
    label: "DCi 4|300N",
    shortName: "DCi 4|300N",
    manufacturer: "Crown",
    modelNumber: "DCi 4|300N",
    searchTerms: ["crown", "dci", "4|300n", "drivecore", "network", "blu link", "70v", "4ch", "amplifier"],
    powerDrawW: 1500,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 362,
    weightKg: 9.1,
    referenceUrl: "https://www.crownaudio.com/en-US/products/dci-4-300n",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 4),
      port("BLU link 1", "ethernet", "bidirectional"),
      port("BLU link 2", "ethernet", "bidirectional"),
      port("Control Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-dci-4-600n",
    deviceType: "amplifier",
    label: "DCi 4|600N",
    shortName: "DCi 4|600N",
    manufacturer: "Crown",
    modelNumber: "DCi 4|600N",
    searchTerms: ["crown", "dci", "4|600n", "drivecore", "network", "blu link", "70v", "4ch", "amplifier"],
    powerDrawW: 3000,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 362,
    weightKg: 9.1,
    referenceUrl: "https://www.crownaudio.com/en-US/product_families/dci-drivecore-series",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 4),
      port("BLU link 1", "ethernet", "bidirectional"),
      port("BLU link 2", "ethernet", "bidirectional"),
      port("Control Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-dci-8-300n",
    deviceType: "amplifier",
    label: "DCi 8|300N",
    shortName: "DCi 8|300N",
    manufacturer: "Crown",
    modelNumber: "DCi 8|300N",
    searchTerms: ["crown", "dci", "8|300n", "drivecore", "network", "blu link", "70v", "8ch", "amplifier"],
    powerDrawW: 3000,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 362,
    weightKg: 10.7,
    referenceUrl: "https://www.crownaudio.com/en-US/products/dci-8-300n",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 8, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 8),
      port("BLU link 1", "ethernet", "bidirectional"),
      port("BLU link 2", "ethernet", "bidirectional"),
      port("Control Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-dci-8-600n",
    deviceType: "amplifier",
    label: "DCi 8|600N",
    shortName: "DCi 8|600N",
    manufacturer: "Crown",
    modelNumber: "DCi 8|600N",
    searchTerms: ["crown", "dci", "8|600n", "drivecore", "network", "blu link", "70v", "8ch", "amplifier"],
    powerDrawW: 6000,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 432,
    weightKg: 13.6,
    referenceUrl: "https://www.crownaudio.com/en-US/product_families/dci-drivecore-series",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 8, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 8),
      port("BLU link 1", "ethernet", "bidirectional"),
      port("BLU link 2", "ethernet", "bidirectional"),
      port("Control Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-dci-2-1250n",
    deviceType: "amplifier",
    label: "DCi 2|1250N",
    shortName: "DCi 2|1250N",
    manufacturer: "Crown",
    modelNumber: "DCi 2|1250N",
    searchTerms: ["crown", "dci", "2|1250n", "drivecore", "network", "blu link", "70v", "2ch", "amplifier"],
    powerDrawW: 3000,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 362,
    weightKg: 10.7,
    referenceUrl: "https://www.crownaudio.com/en-US/products/DCi-2-1250n",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 2, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 2),
      port("BLU link 1", "ethernet", "bidirectional"),
      port("BLU link 2", "ethernet", "bidirectional"),
      port("Control Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-dci-4-1250n",
    deviceType: "amplifier",
    label: "DCi 4|1250N",
    shortName: "DCi 4|1250N",
    manufacturer: "Crown",
    modelNumber: "DCi 4|1250N",
    searchTerms: ["crown", "dci", "4|1250n", "drivecore", "network", "blu link", "70v", "4ch", "amplifier"],
    powerDrawW: 6000,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 432,
    weightKg: 13.6,
    referenceUrl: "https://www.crownaudio.com/en-US/products/dci-4-1250n",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 4),
      port("BLU link 1", "ethernet", "bidirectional"),
      port("BLU link 2", "ethernet", "bidirectional"),
      port("Control Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-dci-2-2400n",
    deviceType: "amplifier",
    label: "DCi 2|2400N",
    shortName: "DCi 2|2400N",
    manufacturer: "Crown",
    modelNumber: "DCi 2|2400N",
    searchTerms: ["crown", "dci", "2|2400n", "drivecore", "network", "blu link", "70v", "2ch", "amplifier"],
    powerDrawW: 6000,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 483,
    weightKg: 10.9,
    referenceUrl: "https://www.crownaudio.com/en-US/products/dci-2-2400n",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 2, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 2),
      port("BLU link 1", "ethernet", "bidirectional"),
      port("BLU link 2", "ethernet", "bidirectional"),
      port("Control Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-dci-4-2400n",
    deviceType: "amplifier",
    label: "DCi 4|2400N",
    shortName: "DCi 4|2400N",
    manufacturer: "Crown",
    modelNumber: "DCi 4|2400N",
    searchTerms: ["crown", "dci", "4|2400n", "drivecore", "network", "blu link", "70v", "4ch", "amplifier"],
    powerDrawW: 12000,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 483,
    weightKg: 13.2,
    referenceUrl: "https://www.crownaudio.com/en-US/products/dci-4-2400n",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 4),
      port("BLU link 1", "ethernet", "bidirectional"),
      port("BLU link 2", "ethernet", "bidirectional"),
      port("Control Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  // ─── DCi DA SERIES (Dante / AES67) ───────────────────────────────────────────

  {
    id: "crown-dci-4-300da",
    deviceType: "amplifier",
    label: "DCi 4|300DA",
    shortName: "DCi 4|300DA",
    manufacturer: "Crown",
    modelNumber: "DCi 4|300DA",
    searchTerms: ["crown", "dci", "4|300da", "drivecore", "dante", "aes67", "70v", "4ch", "amplifier"],
    powerDrawW: 1500,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 362,
    weightKg: 9.1,
    referenceUrl: "https://www.crownaudio.com/en-US/products/dci-4-300da",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 4),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Control Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-dci-4-600da",
    deviceType: "amplifier",
    label: "DCi 4|600DA",
    shortName: "DCi 4|600DA",
    manufacturer: "Crown",
    modelNumber: "DCi 4|600DA",
    searchTerms: ["crown", "dci", "4|600da", "drivecore", "dante", "aes67", "70v", "4ch", "amplifier"],
    powerDrawW: 3000,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 362,
    weightKg: 9.1,
    referenceUrl: "https://www.crownaudio.com/en-US/products/dci-4-600da",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 4),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Control Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-dci-8-300da",
    deviceType: "amplifier",
    label: "DCi 8|300DA",
    shortName: "DCi 8|300DA",
    manufacturer: "Crown",
    modelNumber: "DCi 8|300DA",
    searchTerms: ["crown", "dci", "8|300da", "drivecore", "dante", "aes67", "70v", "8ch", "amplifier", "en54"],
    powerDrawW: 3000,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 362,
    weightKg: 10.7,
    referenceUrl: "https://www.crownaudio.com/en-US/products/dci-8-300da",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 8, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 8),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Control Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-dci-8-600da",
    deviceType: "amplifier",
    label: "DCi 8|600DA",
    shortName: "DCi 8|600DA",
    manufacturer: "Crown",
    modelNumber: "DCi 8|600DA",
    searchTerms: ["crown", "dci", "8|600da", "drivecore", "dante", "aes67", "70v", "8ch", "amplifier", "en54"],
    powerDrawW: 6000,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 432,
    weightKg: 13.6,
    referenceUrl: "https://www.crownaudio.com/en-US/products/dci-8-600da",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 8, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 8),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Control Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-dci-4-1250da",
    deviceType: "amplifier",
    label: "DCi 4|1250DA",
    shortName: "DCi 4|1250DA",
    manufacturer: "Crown",
    modelNumber: "DCi 4|1250DA",
    searchTerms: ["crown", "dci", "4|1250da", "drivecore", "dante", "aes67", "70v", "4ch", "amplifier"],
    powerDrawW: 6000,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 432,
    weightKg: 13.6,
    referenceUrl: "https://www.crownaudio.com/en-US/product_families/dci-drivecore-series",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 4),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Control Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  // ─── CDi SERIES ──────────────────────────────────────────────────────────────

  {
    id: "crown-cdi-1000",
    deviceType: "amplifier",
    label: "CDi 1000",
    shortName: "CDi 1000",
    manufacturer: "Crown",
    modelNumber: "CDi 1000",
    searchTerms: ["crown", "cdi", "1000", "installed", "70v", "140v", "2ch", "500w", "amplifier"],
    powerDrawW: 1200,
    voltage: "100-240V",
    heightMm: 89,    // 2U
    widthMm: 483,
    depthMm: 311,
    weightKg: 8.6,
    referenceUrl: "https://www.crownaudio.com/en-US/products/cdi-1000",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 2, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 2),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-cdi-2000",
    deviceType: "amplifier",
    label: "CDi 2000",
    shortName: "CDi 2000",
    manufacturer: "Crown",
    modelNumber: "CDi 2000",
    searchTerms: ["crown", "cdi", "2000", "installed", "70v", "140v", "2ch", "800w", "amplifier"],
    powerDrawW: 2000,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 311,
    weightKg: 8.6,
    referenceUrl: "https://www.crownaudio.com/en-US/product_families/cdi-series",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 2, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 2),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-cdi-4000",
    deviceType: "amplifier",
    label: "CDi 4000",
    shortName: "CDi 4000",
    manufacturer: "Crown",
    modelNumber: "CDi 4000",
    searchTerms: ["crown", "cdi", "4000", "installed", "70v", "140v", "2ch", "1000w", "amplifier"],
    powerDrawW: 3000,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 311,
    weightKg: 8.6,
    referenceUrl: "https://www.crownaudio.com/en-US/product_families/cdi-series",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 2, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 2),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-cdi-6000",
    deviceType: "amplifier",
    label: "CDi 6000",
    shortName: "CDi 6000",
    manufacturer: "Crown",
    modelNumber: "CDi 6000",
    searchTerms: ["crown", "cdi", "6000", "installed", "70v", "140v", "2ch", "1500w", "amplifier"],
    powerDrawW: 4500,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 416,   // CDi 6000 is deeper
    weightKg: 11.0,
    referenceUrl: "https://www.crownaudio.com/en-US/product_families/cdi-series",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 2, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 2),
      port("AC Power", "power", "input"),
    ],
  },

  // ─── CDi DriveCore SERIES ────────────────────────────────────────────────────

  {
    id: "crown-cdi-dc-2-300",
    deviceType: "amplifier",
    label: "CDi DriveCore 2|300",
    shortName: "CDi DC 2|300",
    manufacturer: "Crown",
    modelNumber: "CDi DriveCore 2|300",
    searchTerms: ["crown", "cdi", "drivecore", "2|300", "installed", "70v", "100v", "2ch", "amplifier"],
    powerDrawW: 750,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 311,
    weightKg: 8.2,
    referenceUrl: "https://www.crownaudio.com/en-US/product_families/cdi-drivecore-series",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 2, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 2),
      port("Control Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-cdi-dc-2-300bl",
    deviceType: "amplifier",
    label: "CDi DriveCore 2|300BL",
    shortName: "CDi DC 2|300BL",
    manufacturer: "Crown",
    modelNumber: "CDi DriveCore 2|300BL",
    searchTerms: ["crown", "cdi", "drivecore", "2|300bl", "blu link", "installed", "70v", "2ch", "amplifier"],
    powerDrawW: 750,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 311,
    weightKg: 8.2,
    referenceUrl: "https://www.crownaudio.com/en-US/product_families/cdi-drivecore-series",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 2, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 2),
      port("BLU link 1", "ethernet", "bidirectional"),
      port("BLU link 2", "ethernet", "bidirectional"),
      port("Control Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "crown-cdi-dc-4-300",
    deviceType: "amplifier",
    label: "CDi DriveCore 4|300",
    shortName: "CDi DC 4|300",
    manufacturer: "Crown",
    modelNumber: "CDi DriveCore 4|300",
    searchTerms: ["crown", "cdi", "drivecore", "4|300", "installed", "70v", "100v", "4ch", "amplifier"],
    powerDrawW: 1500,
    voltage: "100-240V",
    heightMm: 89,
    widthMm: 483,
    depthMm: 311,
    weightKg: 9.0,
    referenceUrl: "https://www.crownaudio.com/en-US/product_families/cdi-drivecore-series",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4, "phoenix"),
      ...ports("Speaker Out", "speaker-level", "output", 4),
      port("Control Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

];
