import { port, ports } from "./_helpers";
import type { DeviceTemplate } from "../types";

/**
 * Symetrix — Complete Product Library
 * DSP processors, I/O expanders, and control endpoints.
 * Source: symetrix.co product pages, verified July 2026.
 * ⚠ Addendum items (specs not published): Edge (physical dims/weight), D100 (physical dims/weight)
 */
export const templates: DeviceTemplate[] = [

  // ─── COGNIO PLATFORM ─────────────────────────────────────────────────────────

  {
    id: "sym-cognio-c20",
    deviceType: "audio-dsp",
    label: "Cognio C20",
    shortName: "C20",
    manufacturer: "Symetrix",
    modelNumber: "C20",
    searchTerms: ["symetrix", "cognio", "c20", "dsp", "dante", "avip", "avoc"],
    powerDrawW: 65,
    voltage: "100-240V",
    heightMm: 44,
    widthMm: 483,
    depthMm: 305,
    weightKg: 3.2,
    referenceUrl: "https://www.symetrix.co/cognio/c20-smart-processor",
    ports: [
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Control Ethernet", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "sym-cognio-c100",
    deviceType: "audio-dsp",
    label: "Cognio C100",
    shortName: "C100",
    manufacturer: "Symetrix",
    modelNumber: "C100",
    searchTerms: ["symetrix", "cognio", "c100", "server", "dsp", "dante"],
    powerDrawW: 120,
    voltage: "100-240V",
    heightMm: 44,
    widthMm: 483,
    depthMm: 380,
    weightKg: 5.0,
    referenceUrl: "https://www.symetrix.co/cognio/c100-smart-processor-server",
    ports: [
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Control Ethernet", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  // ─── PRISM DSP FAMILY ────────────────────────────────────────────────────────

  {
    id: "sym-prism-4x4",
    deviceType: "audio-dsp",
    label: "Prism 4×4",
    shortName: "Prism 4×4",
    manufacturer: "Symetrix",
    modelNumber: "Prism 4×4",
    searchTerms: ["symetrix", "prism", "4x4", "dsp", "dante", "composer"],
    poeDrawW: 25.5,          // PoE+ powered, IEEE 802.3at Class 4
    voltage: "PoE+",
    heightMm: 44,
    widthMm: 208,            // half rack
    depthMm: 238,
    weightKg: 2.3,
    referenceUrl: "https://www.symetrix.co/prism-ip-dsp",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4, "phoenix"),
      ...ports("Analog Out", "analog-audio", "output", 4, "phoenix"),
      port("Dante", "dante", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
    ],
  },

  {
    id: "sym-prism-4x4-dante",
    deviceType: "audio-dsp",
    label: "Prism 4×4 Dante",
    shortName: "Prism 4×4 D",
    manufacturer: "Symetrix",
    modelNumber: "Prism 4×4 with Dante",
    searchTerms: ["symetrix", "prism", "4x4", "dsp", "dante", "composer"],
    poeDrawW: 25.5,
    voltage: "PoE+",
    heightMm: 44,
    widthMm: 208,
    depthMm: 238,
    weightKg: 2.3,
    referenceUrl: "https://www.symetrix.co/prism-ip-dsp",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4, "phoenix"),
      ...ports("Analog Out", "analog-audio", "output", 4, "phoenix"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
    ],
  },

  {
    id: "sym-prism-8x8",
    deviceType: "audio-dsp",
    label: "Prism 8×8",
    shortName: "Prism 8×8",
    manufacturer: "Symetrix",
    modelNumber: "Prism 8×8",
    searchTerms: ["symetrix", "prism", "8x8", "dsp", "composer"],
    powerDrawW: 45,
    voltage: "100-240V",
    heightMm: 44,
    widthMm: 483,
    depthMm: 251,
    weightKg: 4.2,
    referenceUrl: "https://www.symetrix.co/prism-ip-dsp",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 8, "phoenix"),
      ...ports("Analog Out", "analog-audio", "output", 8, "phoenix"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
    ],
  },

  {
    id: "sym-prism-8x8-dante",
    deviceType: "audio-dsp",
    label: "Prism 8×8 Dante",
    shortName: "Prism 8×8 D",
    manufacturer: "Symetrix",
    modelNumber: "Prism 8×8 with Dante",
    searchTerms: ["symetrix", "prism", "8x8", "dsp", "dante", "composer"],
    powerDrawW: 45,
    voltage: "100-240V",
    heightMm: 44,
    widthMm: 483,
    depthMm: 251,
    weightKg: 4.2,
    referenceUrl: "https://www.symetrix.co/prism-ip-dsp",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 8, "phoenix"),
      ...ports("Analog Out", "analog-audio", "output", 8, "phoenix"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
    ],
  },

  {
    id: "sym-prism-12x12",
    deviceType: "audio-dsp",
    label: "Prism 12×12",
    shortName: "Prism 12×12",
    manufacturer: "Symetrix",
    modelNumber: "Prism 12×12",
    searchTerms: ["symetrix", "prism", "12x12", "dsp", "composer"],
    powerDrawW: 56,
    voltage: "100-240V",
    heightMm: 44,
    widthMm: 483,
    depthMm: 251,
    weightKg: 4.2,
    referenceUrl: "https://www.symetrix.co/prism-ip-dsp",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 12, "phoenix"),
      ...ports("Analog Out", "analog-audio", "output", 12, "phoenix"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
    ],
  },

  {
    id: "sym-prism-12x12-dante",
    deviceType: "audio-dsp",
    label: "Prism 12×12 Dante",
    shortName: "Prism 12×12 D",
    manufacturer: "Symetrix",
    modelNumber: "Prism 12×12 with Dante",
    searchTerms: ["symetrix", "prism", "12x12", "dsp", "dante", "composer"],
    powerDrawW: 56,
    voltage: "100-240V",
    heightMm: 44,
    widthMm: 483,
    depthMm: 251,
    weightKg: 4.2,
    referenceUrl: "https://www.symetrix.co/prism-ip-dsp",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 12, "phoenix"),
      ...ports("Analog Out", "analog-audio", "output", 12, "phoenix"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
    ],
  },

  {
    id: "sym-prism-16x16",
    deviceType: "audio-dsp",
    label: "Prism 16×16",
    shortName: "Prism 16×16",
    manufacturer: "Symetrix",
    modelNumber: "Prism 16×16",
    searchTerms: ["symetrix", "prism", "16x16", "dsp", "composer"],
    powerDrawW: 56,
    voltage: "100-240V",
    heightMm: 44,
    widthMm: 483,
    depthMm: 251,
    weightKg: 4.2,
    referenceUrl: "https://www.symetrix.co/prism-ip-dsp",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 16, "phoenix"),
      ...ports("Analog Out", "analog-audio", "output", 16, "phoenix"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
    ],
  },

  {
    id: "sym-prism-16x16-dante",
    deviceType: "audio-dsp",
    label: "Prism 16×16 Dante",
    shortName: "Prism 16×16 D",
    manufacturer: "Symetrix",
    modelNumber: "Prism 16×16 with Dante",
    searchTerms: ["symetrix", "prism", "16x16", "dsp", "dante", "composer"],
    powerDrawW: 56,
    voltage: "100-240V",
    heightMm: 44,
    widthMm: 483,
    depthMm: 251,
    weightKg: 4.2,
    referenceUrl: "https://www.symetrix.co/prism-ip-dsp",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 16, "phoenix"),
      ...ports("Analog Out", "analog-audio", "output", 16, "phoenix"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
    ],
  },

  // ─── RADIUS NX ───────────────────────────────────────────────────────────────

  {
    id: "sym-radius-nx-4x4",
    deviceType: "audio-dsp",
    label: "Radius NX 4×4",
    shortName: "Radius NX 4×4",
    manufacturer: "Symetrix",
    modelNumber: "Radius NX 4×4",
    searchTerms: ["symetrix", "radius", "nx", "4x4", "dsp", "composer", "aec"],
    powerDrawW: 60,
    voltage: "100-240V",
    heightMm: 44,
    widthMm: 483,
    depthMm: 241,
    weightKg: 5.9,
    referenceUrl: "https://www.symetrix.co/radius-nx-ip-dsp",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4, "phoenix"),
      ...ports("Analog Out", "analog-audio", "output", 4, "phoenix"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("Ethernet 3", "ethernet", "bidirectional"),
      port("Ethernet 4", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("RS-232", "serial", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "sym-radius-nx-4x4-dante",
    deviceType: "audio-dsp",
    label: "Radius NX 4×4 Dante",
    shortName: "Radius NX 4×4 D",
    manufacturer: "Symetrix",
    modelNumber: "Radius NX 4×4 with Dante",
    searchTerms: ["symetrix", "radius", "nx", "4x4", "dsp", "dante", "composer", "aec"],
    powerDrawW: 60,
    voltage: "100-240V",
    heightMm: 44,
    widthMm: 483,
    depthMm: 241,
    weightKg: 5.9,
    referenceUrl: "https://www.symetrix.co/radius-nx-ip-dsp",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4, "phoenix"),
      ...ports("Analog Out", "analog-audio", "output", 4, "phoenix"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("RS-232", "serial", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "sym-radius-nx-12x8",
    deviceType: "audio-dsp",
    label: "Radius NX 12×8",
    shortName: "Radius NX 12×8",
    manufacturer: "Symetrix",
    modelNumber: "Radius NX 12×8",
    searchTerms: ["symetrix", "radius", "nx", "12x8", "dsp", "composer", "aec"],
    powerDrawW: 60,
    voltage: "100-240V",
    heightMm: 44,
    widthMm: 483,
    depthMm: 241,
    weightKg: 5.9,
    referenceUrl: "https://www.symetrix.co/radius-nx-ip-dsp",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 12, "phoenix"),
      ...ports("Analog Out", "analog-audio", "output", 8, "phoenix"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("Ethernet 3", "ethernet", "bidirectional"),
      port("Ethernet 4", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("RS-232", "serial", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "sym-radius-nx-12x8-dante",
    deviceType: "audio-dsp",
    label: "Radius NX 12×8 Dante",
    shortName: "Radius NX 12×8 D",
    manufacturer: "Symetrix",
    modelNumber: "Radius NX 12×8 with Dante",
    searchTerms: ["symetrix", "radius", "nx", "12x8", "dsp", "dante", "composer", "aec"],
    powerDrawW: 60,
    voltage: "100-240V",
    heightMm: 44,
    widthMm: 483,
    depthMm: 241,
    weightKg: 5.9,
    referenceUrl: "https://www.symetrix.co/radius-nx-ip-dsp",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 12, "phoenix"),
      ...ports("Analog Out", "analog-audio", "output", 8, "phoenix"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("USB", "usb", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("RS-232", "serial", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  // ─── EDGE ────────────────────────────────────────────────────────────────────
  // ⚠ ADDENDUM: Physical dimensions and weight not published on Edge product page.
  // Dimensions estimated from Radius NX (same 1U form factor). Confirm with Symetrix datasheet.

  {
    id: "sym-edge",
    deviceType: "audio-dsp",
    label: "Edge DSP",
    shortName: "Edge",
    manufacturer: "Symetrix",
    modelNumber: "Edge",
    searchTerms: ["symetrix", "edge", "dsp", "composer", "expansion"],
    powerDrawW: 60,
    voltage: "100-240V",
    heightMm: 44,       // ⚠ estimated — not published
    widthMm: 483,
    depthMm: 241,       // ⚠ estimated — not published
    weightKg: 5.5,      // ⚠ estimated — not published
    referenceUrl: "https://www.symetrix.co/edge-ip-dsp",
    ports: [
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("Ethernet 3", "ethernet", "bidirectional"),
      port("Ethernet 4", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("RS-232", "serial", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "sym-edge-dante",
    deviceType: "audio-dsp",
    label: "Edge DSP Dante",
    shortName: "Edge Dante",
    manufacturer: "Symetrix",
    modelNumber: "Edge with Dante",
    searchTerms: ["symetrix", "edge", "dsp", "dante", "composer", "expansion"],
    powerDrawW: 60,
    voltage: "100-240V",
    heightMm: 44,       // ⚠ estimated
    widthMm: 483,
    depthMm: 241,       // ⚠ estimated
    weightKg: 5.5,      // ⚠ estimated
    referenceUrl: "https://www.symetrix.co/edge-ip-dsp",
    ports: [
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Ethernet 1", "ethernet", "bidirectional"),
      port("Ethernet 2", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("RS-232", "serial", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  // ─── D100 SERVER ─────────────────────────────────────────────────────────────
  // ⚠ ADDENDUM: Physical dimensions, weight, and power draw not published.
  // D100 uses HP Enterprise x86 server platform. Confirm specs with Symetrix.

  {
    id: "sym-d100",
    deviceType: "audio-dsp",
    label: "D100 DSP Server",
    shortName: "D100",
    manufacturer: "Symetrix",
    modelNumber: "D100",
    searchTerms: ["symetrix", "d100", "server", "dsp", "dante", "avip", "enterprise"],
    powerDrawW: 200,    // ⚠ estimated based on HP enterprise platform — not published
    voltage: "100-240V",
    heightMm: 44,       // ⚠ not published — estimated 1U
    widthMm: 483,
    depthMm: 600,       // ⚠ estimated
    weightKg: 10.0,     // ⚠ estimated
    referenceUrl: "https://www.symetrix.co/d100-ip-dsp-server",
    ports: [
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("Control Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  // ─── JUPITER DSP ─────────────────────────────────────────────────────────────

  {
    id: "sym-jupiter-8",
    deviceType: "audio-dsp",
    label: "Jupiter 8",
    shortName: "Jupiter 8",
    manufacturer: "Symetrix",
    modelNumber: "Jupiter 8",
    searchTerms: ["symetrix", "jupiter", "8", "dsp", "zone", "app"],
    powerDrawW: 25,
    voltage: "100-240V",
    heightMm: 44,
    widthMm: 483,
    depthMm: 200,
    weightKg: 3.0,
    referenceUrl: "https://www.symetrix.co/jupiter-dsp",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 8, "phoenix"),
      ...ports("Analog Out", "analog-audio", "output", 8, "phoenix"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "sym-jupiter-4",
    deviceType: "audio-dsp",
    label: "Jupiter 4",
    shortName: "Jupiter 4",
    manufacturer: "Symetrix",
    modelNumber: "Jupiter 4",
    searchTerms: ["symetrix", "jupiter", "4", "dsp", "zone", "app"],
    powerDrawW: 20,
    voltage: "100-240V",
    heightMm: 44,
    widthMm: 483,
    depthMm: 200,
    weightKg: 2.5,
    referenceUrl: "https://www.symetrix.co/jupiter-dsp",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4, "phoenix"),
      ...ports("Analog Out", "analog-audio", "output", 4, "phoenix"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("GPIO", "gpio", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  // ─── ZONE MIX 761 ────────────────────────────────────────────────────────────

  {
    id: "sym-zone-mix-761",
    deviceType: "audio-dsp",
    label: "Zone Mix 761",
    shortName: "Zone Mix 761",
    manufacturer: "Symetrix",
    modelNumber: "Zone Mix 761",
    searchTerms: ["symetrix", "zone mix", "761", "dsp", "zone", "paging", "restaurant"],
    powerDrawW: 30,
    voltage: "100-240V",
    heightMm: 44,
    widthMm: 483,
    depthMm: 200,
    weightKg: 3.0,
    referenceUrl: "https://www.symetrix.co/zone-mix-761-dsp",
    ports: [
      ...ports("Mic/Line In", "analog-audio", "input", 6, "phoenix"),
      ...ports("Zone Out", "analog-audio", "output", 6, "phoenix"),
      port("Paging In", "analog-audio", "input", "phoenix"),
      port("Ethernet", "ethernet", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  // ─── xIO EXPANDERS ───────────────────────────────────────────────────────────

  {
    id: "sym-xin-4",
    deviceType: "audio-interface",
    label: "xIn 4",
    shortName: "xIn 4",
    manufacturer: "Symetrix",
    modelNumber: "xIn 4",
    searchTerms: ["symetrix", "xin", "xio", "expander", "dante", "analog input"],
    poeDrawW: 13,
    heightMm: 44,
    widthMm: 210,   // half rack
    depthMm: 110,
    weightKg: 0.5,
    referenceUrl: "https://www.symetrix.co/xio-expanders",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4, "phoenix"),
      port("Dante", "dante", "bidirectional"),
    ],
  },

  {
    id: "sym-xout-4",
    deviceType: "audio-interface",
    label: "xOut 4",
    shortName: "xOut 4",
    manufacturer: "Symetrix",
    modelNumber: "xOut 4",
    searchTerms: ["symetrix", "xout", "xio", "expander", "dante", "analog output"],
    poeDrawW: 13,
    heightMm: 44,
    widthMm: 210,
    depthMm: 110,
    weightKg: 0.5,
    referenceUrl: "https://www.symetrix.co/xio-expanders",
    ports: [
      ...ports("Analog Out", "analog-audio", "output", 4, "phoenix"),
      port("Dante", "dante", "bidirectional"),
    ],
  },

  {
    id: "sym-xio-4x4",
    deviceType: "audio-interface",
    label: "xIO 4×4",
    shortName: "xIO 4×4",
    manufacturer: "Symetrix",
    modelNumber: "xIO 4×4",
    searchTerms: ["symetrix", "xio", "4x4", "expander", "dante", "analog"],
    poeDrawW: 13,
    heightMm: 44,
    widthMm: 210,
    depthMm: 110,
    weightKg: 0.5,
    referenceUrl: "https://www.symetrix.co/xio-expanders",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 4, "phoenix"),
      ...ports("Analog Out", "analog-audio", "output", 4, "phoenix"),
      port("Dante", "dante", "bidirectional"),
    ],
  },

  {
    id: "sym-xin-12",
    deviceType: "audio-interface",
    label: "xIn 12",
    shortName: "xIn 12",
    manufacturer: "Symetrix",
    modelNumber: "xIn 12",
    searchTerms: ["symetrix", "xin", "12", "xio", "expander", "dante", "analog input"],
    powerDrawW: 30,
    voltage: "100-240V",
    heightMm: 44,
    widthMm: 483,
    depthMm: 200,
    weightKg: 2.0,
    referenceUrl: "https://www.symetrix.co/xio-expanders",
    ports: [
      ...ports("Analog In", "analog-audio", "input", 12, "phoenix"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "sym-xout-12",
    deviceType: "audio-interface",
    label: "xOut 12",
    shortName: "xOut 12",
    manufacturer: "Symetrix",
    modelNumber: "xOut 12",
    searchTerms: ["symetrix", "xout", "12", "xio", "expander", "dante", "analog output"],
    powerDrawW: 30,
    voltage: "100-240V",
    heightMm: 44,
    widthMm: 483,
    depthMm: 200,
    weightKg: 2.0,
    referenceUrl: "https://www.symetrix.co/xio-expanders",
    ports: [
      ...ports("Analog Out", "analog-audio", "output", 12, "phoenix"),
      port("Dante Primary", "dante", "bidirectional"),
      port("Dante Secondary", "dante", "bidirectional"),
      port("AC Power", "power", "input"),
    ],
  },

  {
    id: "sym-xio-stage-4x4",
    deviceType: "audio-interface",
    label: "xIO Stage 4×4",
    shortName: "xIO Stage",
    manufacturer: "Symetrix",
    modelNumber: "xIO Stage 4×4",
    searchTerms: ["symetrix", "xio", "stage", "4x4", "expander", "dante", "xlr", "snake"],
    poeDrawW: 13,
    referenceUrl: "https://www.symetrix.co/xio-expanders",
    ports: [
      ...ports("XLR In", "analog-audio", "input", 4, "xlr-3"),
      ...ports("XLR Out", "analog-audio", "output", 4, "xlr-3"),
      port("Dante", "dante", "bidirectional"),
    ],
  },

  // ─── xIO BLUETOOTH ENDPOINTS ─────────────────────────────────────────────────

  {
    id: "sym-xio-bluetooth",
    deviceType: "audio-interface",
    label: "xIO Bluetooth",
    shortName: "xIO BT",
    manufacturer: "Symetrix",
    modelNumber: "xIO Bluetooth",
    searchTerms: ["symetrix", "xio", "bluetooth", "dante", "endpoint", "wall plate"],
    poeDrawW: 7,
    referenceUrl: "https://www.symetrix.co/xio-bluetooth-endpoints",
    ports: [
      port("Bluetooth", "bluetooth", "bidirectional"),
      port("Dante", "dante", "bidirectional"),
    ],
  },

  // ─── ARC WALL CONTROLLERS ────────────────────────────────────────────────────

  {
    id: "sym-arc-3",
    deviceType: "controller",
    label: "ARC-3",
    shortName: "ARC-3",
    manufacturer: "Symetrix",
    modelNumber: "ARC-3",
    searchTerms: ["symetrix", "arc", "arc-3", "wall plate", "controller", "remote", "touch"],
    referenceUrl: "https://www.symetrix.co/arc-series-controllers",
    ports: [
      port("ARC Bus", "ethernet", "bidirectional"),
    ],
  },

  {
    id: "sym-arc-2e",
    deviceType: "controller",
    label: "ARC-2e",
    shortName: "ARC-2e",
    manufacturer: "Symetrix",
    modelNumber: "ARC-2e",
    searchTerms: ["symetrix", "arc", "arc-2e", "wall plate", "controller", "remote"],
    referenceUrl: "https://www.symetrix.co/arc-series-controllers",
    ports: [
      port("ARC Bus", "ethernet", "bidirectional"),
    ],
  },

  {
    id: "sym-arc-k1e",
    deviceType: "controller",
    label: "ARC-K1e",
    shortName: "ARC-K1e",
    manufacturer: "Symetrix",
    modelNumber: "ARC-K1e",
    searchTerms: ["symetrix", "arc", "arc-k1e", "wall plate", "controller", "volume knob"],
    referenceUrl: "https://www.symetrix.co/arc-series-controllers",
    ports: [
      port("ARC Bus", "ethernet", "bidirectional"),
    ],
  },

  {
    id: "sym-arc-sw4e",
    deviceType: "controller",
    label: "ARC-SW4e",
    shortName: "ARC-SW4e",
    manufacturer: "Symetrix",
    modelNumber: "ARC-SW4e",
    searchTerms: ["symetrix", "arc", "arc-sw4e", "wall plate", "controller", "switches"],
    referenceUrl: "https://www.symetrix.co/arc-series-controllers",
    ports: [
      port("ARC Bus", "ethernet", "bidirectional"),
    ],
  },

  {
    id: "sym-arc-pse",
    deviceType: "controller",
    label: "ARC-PSe",
    shortName: "ARC-PSe",
    manufacturer: "Symetrix",
    modelNumber: "ARC-PSe",
    searchTerms: ["symetrix", "arc", "arc-pse", "power supply", "distribution", "half rack"],
    powerDrawW: 24,
    heightMm: 44,
    widthMm: 208,   // half rack
    depthMm: 229,
    weightKg: 2.0,
    referenceUrl: "https://www.symetrix.co/arc-series-controllers",
    ports: [
      port("ARC In (from DSP)", "ethernet", "input"),
      ...ports("ARC Out", "ethernet", "output", 8),
      port("AC Power", "power", "input"),
    ],
  },

  // ─── W-SERIES CONTROLLERS ────────────────────────────────────────────────────

  {
    id: "sym-w1",
    deviceType: "controller",
    label: "W1 Controller",
    shortName: "W1",
    manufacturer: "Symetrix",
    modelNumber: "W1",
    searchTerms: ["symetrix", "w1", "w series", "wall plate", "controller", "ip", "oled"],
    poeDrawW: 5,
    referenceUrl: "https://www.symetrix.co/w-series-controllers",
    ports: [
      port("Ethernet (PoE)", "ethernet", "bidirectional"),
    ],
  },

  {
    id: "sym-w2",
    deviceType: "controller",
    label: "W2 Controller",
    shortName: "W2",
    manufacturer: "Symetrix",
    modelNumber: "W2",
    searchTerms: ["symetrix", "w2", "w series", "wall plate", "controller", "ip", "oled"],
    poeDrawW: 5,
    referenceUrl: "https://www.symetrix.co/w-series-controllers",
    ports: [
      port("Ethernet (PoE)", "ethernet", "bidirectional"),
    ],
  },

  {
    id: "sym-w3",
    deviceType: "controller",
    label: "W3 Controller",
    shortName: "W3",
    manufacturer: "Symetrix",
    modelNumber: "W3",
    searchTerms: ["symetrix", "w3", "w series", "wall plate", "controller", "ip", "oled"],
    poeDrawW: 5,
    referenceUrl: "https://www.symetrix.co/w-series-controllers",
    ports: [
      port("Ethernet (PoE)", "ethernet", "bidirectional"),
    ],
  },

  // ─── T-SERIES TOUCHSCREENS ───────────────────────────────────────────────────

  {
    id: "sym-t5-glass",
    deviceType: "controller",
    label: "T-5 Touchscreen",
    shortName: "T-5",
    manufacturer: "Symetrix",
    modelNumber: "T-5 Glass",
    searchTerms: ["symetrix", "t5", "t-5", "touchscreen", "glass", "controller", "5 inch"],
    poeDrawW: 15,
    referenceUrl: "https://www.symetrix.co/t-series-touchscreen-controllers",
    ports: [
      port("Ethernet (PoE)", "ethernet", "bidirectional"),
    ],
  },

  {
    id: "sym-t7-glass",
    deviceType: "controller",
    label: "T-7 Touchscreen",
    shortName: "T-7",
    manufacturer: "Symetrix",
    modelNumber: "T-7 Glass",
    searchTerms: ["symetrix", "t7", "t-7", "touchscreen", "glass", "controller", "7 inch"],
    poeDrawW: 15,
    referenceUrl: "https://www.symetrix.co/t-series-touchscreen-controllers",
    ports: [
      port("Ethernet (PoE)", "ethernet", "bidirectional"),
    ],
  },

  {
    id: "sym-t10-glass",
    deviceType: "controller",
    label: "T-10 Touchscreen",
    shortName: "T-10",
    manufacturer: "Symetrix",
    modelNumber: "T-10 Glass",
    searchTerms: ["symetrix", "t10", "t-10", "touchscreen", "glass", "controller", "10 inch"],
    poeDrawW: 20,
    referenceUrl: "https://www.symetrix.co/t-series-touchscreen-controllers",
    ports: [
      port("Ethernet (PoE)", "ethernet", "bidirectional"),
    ],
  },

];
